name: biomag2020
dependencies:
  - python=3.7.7
  - pip=20.0.2
  - ipykernel=5.1.4
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - conda-forge::mne=0.20.5
  - conda-forge::mne-bids=0.4
  - bioconda::snakemake-minimal=5.3.0
  - conda-forge::papermill=2.2.2
  - conda-forge::pot=0.7.0
  - conda-forge::pyclustering=0.10.1.2
  - pip:
    - git+git://github.com/kalenkovich/pybids.git@kalenkovich_make-_validate_file-work-on-windows#egg=pybids
