name: biomag2020
dependencies:
  - python=3.7.7
  - pip=20.0.2
  - ipykernel=5.1.4
  - jupyter
  - conda-forge::mne=0.20.5
  - conda-forge::mne-bids=2.2.2
  - bioconda::snakemake-minimal=5.3.0
  - conda-forge::papermill=5.3.1
  - pip:
    - git+git://github.com/kalenkovich/pybids.git@kalenkovich_make-_validate_file-work-on-windows#egg=pybids